### ISSUE TITLE
Webhook url gives 404 error

### ISSUE THREAD

**Issue by runekaagaard** [moneypark/redmine-github-pull-requests-tool#1]
Hi @moneypark, This plugin looks very interesting, thx for that! After setting up the plugin as per the instructions in the README the url for the github webhook mentioned seems to be wrong. I'm on redmine 4.1 and  ruby 2.6.6p146. This shows up in `log/production.log`:

```
Started POST "/github_api_endpoints/pull_request/" for 140.82.115.240 at 2021-01-13 10:00:29 +0100
  
ActionController::RoutingError (No route matches [POST] "/github_api_endpoints/pull_request"):
  
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `block in call'
vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'
vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'
vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `call'
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
vendor/bundle/ruby/2.6.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/static.rb:127:in `call'
vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:524:in `call'
vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by wiesion** [comment]
Hello Rune, are you sure you restarted Redmine?

```ActionController::RoutingError (No route matches [POST] "/github_api_endpoints/pull_request")```

seems to indicate that `config/routes.rb` was not loaded.

**Comment by runekaagaard** [comment]
Hi @wiesion. Yes I did restart redmine. This plugin shows up under administration and is configurable. I noticed that I don't have any resembling routes:

```
$ bin/rails routes | grep pull
                       github_webhooks POST               /github_webhooks(.:format)                                                     pull_requests#create {:formats=>:json}
````

**Comment by runekaagaard** [comment]
I got it working by calling `mysite.com/github_webhooks` instead.

**Comment by wiesion** [comment]
Hello Rune, yes i only noticed now that my documentation contained the wrong URL, i have corrected it now. Thanks for bringing this to our attention 👍
